trigger:
  - master

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 10.x
            displayName: Install Node.js

          - bash: |
              set -x

              whoami
              pwd
              ls -lA ./

              which node
              which yarn
              node -v
              yarn -v
            displayName: Debugging

          - bash: |
              yarn build
            displayName: Yarn install and build

          - publish: $(Build.SourcesDirectory)/dist
            artifact: WebApp

  - stage: Deploy
    jobs:
      - job: Deploy
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: none

          - download: current
            artifact: WebApp

          - bash: |
              set -x

              whoami
              pwd
              ls -lA ./
              ls -lA ./*

              which node
              which yarn
              node -v
              yarn -v
            workingDirectory: $(Pipeline.Workspace)
            displayName: Debugging
