trigger:
  - master

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 10.x
            displayName: Install Node.js

          - bash: |
              set -x

              whoami
              pwd
              ls -lA ./

              which node
              which yarn
              node -v
              yarn -v
            displayName: Debugging

          - bash: |
              yarn build
            displayName: Install dependencies and build

          - publish: $(Build.SourcesDirectory)/dist
            artifact: WebApp

      - job: Test
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: |
              set -x

              whoami
              pwd
              ls -lA ./

              which node
              which yarn
              node -v
              yarn -v
            displayName: Debugging

          - bash: |
              yarn test
            displayName: Run tests

  - stage: Deploy
    jobs:
      - deployment: Release
        pool:
          vmImage: ubuntu-latest
        environment: smarthotel-dev.web
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: |
                    set -x

                    whoami
                    pwd
                    ls -lA ./
                    ls -lA ./*

                    which node
                    which yarn
                    node -v
                    yarn -v
                  workingDirectory: $(Pipeline.Workspace)
                  displayName: Debugging
