trigger:
  - master

stages:
  - stage: Build & Test
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: |
              set -x

              whoami
              pwd
              ls -lA ./

              which node
              which yarn
              node -v
              yarn -v
            displayName: Debugging

          - bash: |
              yarn build
            displayName: Install dependencies and build

          - publish: $(Build.SourcesDirectory)/dist
            artifact: WebApp

      - job: Test
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: |
              set -x

              whoami
              pwd
              ls -lA ./

              which node
              which yarn
              node -v
              yarn -v
            displayName: Debugging

          - bash: |
              yarn test
            displayName: Run tests

  - template: release.tmpl.yml
    parameters:
      environment: dev1
