trigger: none
pr: none
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight release
    branches:
      include:
        - master

stages:
  - stage: Release
    jobs:
      - deployment: Release
        pool:
          vmImage: ubuntu-latest
        environment: staging
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: specific
                    project: '90649f0f-0fae-4c93-bd10-36f077330d47'
                    definition: '8'
                    specificBuildWithTriggering: true
                    buildVersionToDownload: latest

                - bash: |
                    set -x

                    whoami
                    pwd
                    ls -lA ./
                    ls -lA ./*
                  workingDirectory: $(Pipeline.Workspace)
                  displayName: Debugging
