parameters:
  environment: ""

stages:
  - stage: Release
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: ${{ parameters.vmImage }}
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: |
                    set -x

                    whoami
                    pwd
                    ls -lA ./
                    ls -lA ./*

                    which node
                    which yarn
                    node -v
                    yarn -v
                  workingDirectory: $(Pipeline.Workspace)
                  displayName: Debugging
