trigger: none
pr: none
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight release
    branches:
      include:
        - master

stages:
  - template: ./release.tmpl.yml
    parameters:
      environment: staging
      standalone: true
