parameters:
  environment: ""
  standalone: false

stages:
  - stage: Release
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - ${{ if eq(parameters.standalone, 'true') }}:
                    - task: DownloadPipelineArtifact@2
                      inputs:
                        buildType: specific
                        project: "$(System.TeamProjectId)"
                        definition: "8"
                        specificBuildWithTriggering: true
                        buildVersionToDownload: latest

                - bash: |
                    set -x

                    whoami
                    pwd
                    ls -lA ./
                    ls -lA ./*

                    which node
                    which yarn
                    node -v
                    yarn -v
                  workingDirectory: $(Pipeline.Workspace)
                  displayName: Debugging
